### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by nodiscc** [j84/99ko#5]
Hello, each file in the project has a copyright header

> - For the full copyright and license information, please view the LICENSE
> - file that was distributed with this source code.

However there is no LICENSE file distributed with the project or on your website. Which license is 99ko released under?

Ref. https://github.com/Kickball/awesome-selfhosted/pull/725

Thanks in advance.

**Comment by j84** [comment]
99ko is open source (GNU)

**Comment by meitar** [comment]
@j84 Thanks for working on this project. :)

Thing is, I still don't know what license you've chosen. "Open source (GNU)" is still an ambiguous answer. Can you please clarify which license, specifically, you are using? A list of all known licenses can be seen on the [SPDX License List](https://spdx.org/licenses/).

The best way to do this is to add a LICENSE file to your repository. Please see [the GitHub help guides on how to license your code](https://help.github.com/articles/licensing-a-repository/) if you have not done this before.

I am asking for clarification on behalf of Kickball/awesome-selfhosted#761, which I am following up on. Thank you again for your work!
