### ISSUE TITLE
Petit bug sur l'appel CSS des plugins dans l'administration.

### ISSUE THREAD

**Issue by starckio** [j84/99ko#9]
Je remarque que dans l'administration tous les fichier CSS des plugins son chargé..
Es-que c'est normal ?

L'appel devrait se faire seulement quand on se trouve sur la page même du plugin car si plusieurs plugins ont la même structure, les styles se mélange…

**Comment by j84** [comment]
C'est normal, pas de soucis car il y a toujours une classe préfixant (identifiantduplugin-admin) : 

`.pluginsmanager-admin td .description{
    opacity: 0;
    clear: both;
    margin-top: 10px;
}`
